# Generated by Django 4.2.7 on 2024-01-23 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0008_alter_events_latitude_alter_events_longitude'),
        ('payment', '0003_eventbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='order',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizer.events'),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='numTickets',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='totalPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='visitor_names',
            field=models.JSONField(null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
