# Generated by Django 4.2.7 on 2024-01-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_eventbooking_order_eventbooking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
