# Generated by Django 4.2.7 on 2024-01-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorOrganizerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_user_id', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='organizer',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
