# Generated by Django 4.2.7 on 2024-02-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_pendingchat_event_pendingchat_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingchat',
            old_name='organizer',
            new_name='reciever',
        ),
    ]
