# Generated by Django 4.2.7 on 2024-02-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='event',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatNotification',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
