# Generated by Django 4.2.7 on 2024-01-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='date',
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timeslots',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
