# Generated by Django 4.2.7 on 2024-01-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_agegroup_tickettype'),
        ('organizer', '0002_remove_timeslots_date_alter_timeslots_endtime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettype',
            name='event',
        ),
        migrations.RemoveField(
            model_name='timeslots',
            name='event',
        ),
        migrations.AlterField(
            model_name='ticketprice',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.agegroup'),
        ),
        migrations.AlterField(
            model_name='ticketprice',
            name='ticket_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.tickettype'),
        ),
        migrations.AlterField(
            model_name='ticketquantity',
            name='age_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.agegroup'),
        ),
        migrations.AlterField(
            model_name='ticketquantity',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.tickettype'),
        ),
        migrations.DeleteModel(
            name='AgeGroup',
        ),
        migrations.DeleteModel(
            name='TicketType',
        ),
        migrations.DeleteModel(
            name='TimeSlots',
        ),
    ]
