# Generated by Django 4.2.7 on 2024-01-13 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_agegroup_tickettype'),
        ('organizer', '0003_remove_tickettype_event_remove_timeslots_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.agegroup')),
            ],
        ),
        migrations.RemoveField(
            model_name='ticketquantity',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='ticketquantity',
            name='event',
        ),
        migrations.RemoveField(
            model_name='ticketquantity',
            name='type',
        ),
        migrations.AddField(
            model_name='events',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='is_availabe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='events',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='TicketPrice',
        ),
        migrations.DeleteModel(
            name='TicketQuantity',
        ),
        migrations.AddField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.events'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.tickettype'),
        ),
    ]
