# Generated by Django 4.2.7 on 2024-01-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_alter_events_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='title',
        ),
    ]
