# Generated by Django 4.2.7 on 2024-01-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0007_remove_events_is_availabe_remove_events_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=40, max_digits=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=40, max_digits=50, null=True),
        ),
    ]
