# Generated by Django 4.2.7 on 2024-02-28 15:58

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizer", "0008_alter_events_latitude_alter_events_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
    ]
